// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyses.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getAnalysisByRetroID = `-- name: GetAnalysisByRetroID :one
SELECT id, retro_id, result, created_at FROM analyses WHERE retro_id = $1
`

func (q *Queries) GetAnalysisByRetroID(ctx context.Context, retroID uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysisByRetroID, retroID)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.RetroID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAnalysis = `-- name: UpsertAnalysis :one
INSERT INTO analyses (retro_id, result)
VALUES ($1, $2)
ON CONFLICT (retro_id) DO UPDATE SET result = EXCLUDED.result, created_at = now()
RETURNING id, retro_id, result, created_at
`

type UpsertAnalysisParams struct {
	RetroID uuid.UUID       `json:"retro_id"`
	Result  json.RawMessage `json:"result"`
}

func (q *Queries) UpsertAnalysis(ctx context.Context, arg UpsertAnalysisParams) (Analysis, error) {
	row := q.db.QueryRow(ctx, upsertAnalysis, arg.RetroID, arg.Result)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.RetroID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}
