// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (retro_id, column_type, content, author_name)
VALUES ($1, $2, $3, $4)
RETURNING id, retro_id, column_type, content, author_name, created_at
`

type CreateCardParams struct {
	RetroID    uuid.UUID `json:"retro_id"`
	ColumnType string    `json:"column_type"`
	Content    string    `json:"content"`
	AuthorName string    `json:"author_name"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.RetroID,
		arg.ColumnType,
		arg.Content,
		arg.AuthorName,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.RetroID,
		&i.ColumnType,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1 AND retro_id = $2
`

type DeleteCardParams struct {
	ID      uuid.UUID `json:"id"`
	RetroID uuid.UUID `json:"retro_id"`
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) error {
	_, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.RetroID)
	return err
}

const getCardsByRetroID = `-- name: GetCardsByRetroID :many
SELECT id, retro_id, column_type, content, author_name, created_at FROM cards WHERE retro_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetCardsByRetroID(ctx context.Context, retroID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCardsByRetroID, retroID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.RetroID,
			&i.ColumnType,
			&i.Content,
			&i.AuthorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
