// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Analysis struct {
	ID        uuid.UUID       `json:"id"`
	RetroID   uuid.UUID       `json:"retro_id"`
	Result    json.RawMessage `json:"result"`
	CreatedAt time.Time       `json:"created_at"`
}

type Card struct {
	ID         uuid.UUID `json:"id"`
	RetroID    uuid.UUID `json:"retro_id"`
	ColumnType string    `json:"column_type"`
	Content    string    `json:"content"`
	AuthorName string    `json:"author_name"`
	CreatedAt  time.Time `json:"created_at"`
}

type Retro struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
