// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retros.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRetro = `-- name: CreateRetro :one
INSERT INTO retros (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateRetro(ctx context.Context, name string) (Retro, error) {
	row := q.db.QueryRow(ctx, createRetro, name)
	var i Retro
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getRetro = `-- name: GetRetro :one
SELECT id, name, created_at FROM retros WHERE id = $1
`

func (q *Queries) GetRetro(ctx context.Context, id uuid.UUID) (Retro, error) {
	row := q.db.QueryRow(ctx, getRetro, id)
	var i Retro
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listRetros = `-- name: ListRetros :many
SELECT id, name, created_at FROM retros ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListRetros(ctx context.Context) ([]Retro, error) {
	rows, err := q.db.Query(ctx, listRetros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Retro{}
	for rows.Next() {
		var i Retro
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
